Fix mock problem when native rpmdb format is different from chroot's.
When the problem is present, the logs will have:
===
rpmdb: /var/lib/rpm/Name: unexpected file type or format
error: cannot open Name index using db3 - Invalid argument (22)
===

See: https://bugzilla.redhat.com/show_bug.cgi?id=1357787

Since the rebuild is fast and doesn't hurt when the format's are the
same, just do the rebuild all the time.